### ISSUE TITLE
a problem

### ISSUE THREAD

**Issue by akka-4** [akka-4/22clin#5]
hi So Seol.
I was proceeding with the 22clin project in the direction that you recommend. But I found a problem

 HTML document cannot be connected to CSS documents. I need to link the CSS files to the HTML document with <link>, so should I connect the CSS files to the 'src' folder altogether?

The sentence may be a little strange because I am not good at English. I should study English hard :(

**Comment by akka-4** [comment]
if you need my files, call me...

However, I can only be contacted from 8 a.m., 9 p.m. and 10 p.m. to 1 p.m. in Korean time.

**Comment by ghost** [comment]
Hmm... All first, I am so sorry to answer late. Then, I can not answer because I do not know how did you try to connect HTML and CSS files. Can you show me a little bit piece of code?

**Comment by ghost** [comment]
And then, you have to import from the CSS files that you created right before to the main CSS file that is in `src/css/styles.css`. As I told you, the HTML files are connected to the main CSS file only, and the main CSS file will import all of the CSS files that you want to add. So, you have to import them. Without import, all process will be broken.

**Comment by akka-4** [comment]
I have pulled it on my computer and copied it exactly as you posted it. By the way, the html document keeps opening, but I don't think I can find the css document. I tried to rewrite the route, but it didn't work. Can I put the css files in the pages folder?

**Comment by ghost** [comment]
Hmm... I think that you can not understand. Ok, Let's go to the folder tree world.

Basically, the `src` folder is the folder that has all of the sources of this service. So, you have to create files in `src` such as html, css, javascript files.

Out of them, there are many configuration files. `package.json`, `README.md`, `eslintrc.js` etc files are for configuring.

Ok?

And then, in the `src` folder, there are three folders, `pages`, `css` and `js`.

`pages` folder contains all of the html files that this website is using. So, if you want to create routes, just create a html file in `src/pages` folder. And write a code.

`css` folder contains all of the css files that this service is using. So, if you want to add some of the styles on this website, create a css file in `src/css` folder. But! To add styles has rules.

First, you have to `import` all of the css files which is placed in folders that is in `src/css`. So, because html import just one css file `src/css/styles.css`, you have to import all of the css files to `src/css/styles.css`. As you can see the `src/css/styles.css`, that file imports all of the css files. Check it and apply.

And then, in `src/css` folder, there are two folders, `screens` and `components`. `screens` is the folder that is for the css files which is for adding styles to each pages. Now, because you have only one page, there is just only one css file. `components` is the folder that is for the css files which is for add styles to components. `Components` means the repeated part in a service.

You can create any folder for css files to maintain this service more easily.

Do you understand? If not, please ask to me again, again, again. I think that you are first time to code right? I hope you to learn about Computer Programming more. So, thank you for reading and ask me!

**Comment by akka-4** [comment]
Thank you!!

I read your explanation and I'll aplly them.

**Comment by ghost** [comment]
Nice.
